Phase
UdL-EPS-SoftArch/AcademicRecruit-GEI pull request #37
Opened 2021-06-26 17:14 UTC by valcobe

2021-06-27 15:44 UTC, rogargon commented
There are some code style errors detected by `ng lint` that need fixing before PR acceptance:

```
Linting "academicrecruit-gei"...

/home/runner/work/AcademicRecruit-GEI/AcademicRecruit-GEI/src/app/qualification/qualification-edit/qualification-edit.component.ts:23:43
Lint errors found in the listed files.
ERROR: 23:43  semicolon  Missing semicolon

/home/runner/work/AcademicRecruit-GEI/AcademicRecruit-GEI/src/app/qualification/qualification-list/qualification-list.component.ts:20:5
ERROR: 20:5   align      parameters are not aligned
```

2021-06-28 09:15 UTC, rogargon commented
Phases are not created (404 error). Please, check the implemented features are actually working as expected

2021-06-29 08:39 UTC, bergacat1 requested changes, later dismissed
Phase's `phaseNumber` and `name` are not stored. Moreover, you could indicate the format of the dates (ideally you should place a date picker).

2021-06-29 08:39 UTC, bergacat1 commented on src/app/phase/phase-create/phase-create.component.html
> +        <input id="name" name="name" class="form-control" [(ngModel)]="phase.phasenumber"/>
This field should be related to `phase.name`.

2021-06-29 08:39 UTC, bergacat1 commented on src/app/phase/phase-create/phase-create.component.html
> +        <input id="phasenumber" name="phasenumber" class="form-control" required [(ngModel)]="phase.phasenumber"/>
This field is called `phaseNumber` in the API and, thus, it should be called the same at Phase class of the client side.

2021-06-29 21:29 UTC, rogargon approved these changes

2021-06-29 21:30 UTC, merged